language: node_js
node_js:
- node
script:
- echo 'script'
deploy:
  provider: s3
  access_key_id: AKIAJTYARGTVL6WJVVNQ
  secret_access_key:
    secure: D8l/rQDCuwVSums/V8mRlOzR0rpvm/Urxjx2CQ/2nJEFs6IG1DUq0jO1bu2hssKPnvHxVZJR+Jq9cAVybh3q5CKfPYPBrEDFNlnvaLkffjtSy43u9YZYCxz5eRtxhW/wMkKHXt7KeyOEoLWdYzLSR9rpW6LQ6AV5JkYReNBY40U=
  bucket: www.marinaspeech.com
  acl: public_read
branches:
  only:
  - master
