language: node_js
node_js:
- node
script:
- echo 'script'
deploy:
  provider: s3
  access_key_id: AKIAJTYARGTVL6WJVVNQ
  secret_access_key:
    secure: 1fhts0DhBVUPJ+X1Gxnzazx+racsxu2pvxnNGzqbXmVzQPP3bg7dnf1AX0wCp2nmGzUDhAXlq+oyFab8tlB6eLto9dvdorqiro8DsuJhLtXndjb04C81tPqTRAzgFn5s6tKl6kAjqyL87oWaGOIXTgkEbq8Gw+SLKcyT+YVUBQk=
  bucket: www.marinaspeech.com
  acl: public_read
branches:
  only:
  - master
